spring.application.name=EventOrganiser

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/event_organizer_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=m0fNyVcXOi7fqs3m9R4qUSNaMniHqLVCVxdTDc7dnilxyrR8U2R7K68BDsgMrT7VhMNXU134eM4eZdRmPkOvtA==
jwt.expiration.ms=86400000

logging.level.root=INFO
logging.level.com.eventorganiser==DEBUG
logging.level.org.hibernate.SQL=DEBUG